language: node_js
node_js:
    - "10.16.0/*"
notifications:
    email: false
sudo: required
script: skip
services:
    - docker
before_install:
    - sudo chown -R travis:travis $HOME/docker
cache:
    directories:
        - $HOME/docker

addons:
    apt:
        packages:
            - google-chrome-stable
env:
    global:
        - DOCKER_IMAGE='ashishmotanam/carbon-graphs'
        - TAG="${TRAVIS_PULL_REQUEST_SHA:=latest}"
branches:
    only:
        - main
        - /^greenkeeper/.*$/
jobs:
    include:
        - stage: test
          before_install: true
          script:
              - npm run test
        - script:
              - USE_SELENIUM_GRID=true npm run wdio
        - stage: lint
          script: npm run lint
        - stage: build
          script: npm run build
        - script: npm run build:dist
        - stage: release
          node_js: lts/*
          script: skip
          deploy:
              provider: script
              skip_cleanup: true
              script: npx semantic-release
              on:
                  branch: main
        - stage: deploy
          name: "Deploy to gh-pages"
          script: skip
          before_deploy:
              - npm run build:site
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              local_dir: .site
              on:
                  branch: main
stages:
    - lint
    - test
    - build
    - name: release
      if: type != pull_request
    - name: deploy
      if: type != pull_request
