language: node_js
node_js:
    - "10.16.0/*"
notifications:
    email: false
sudo: required
script: skip
services:
    - docker
    - xvfb

addons:
    apt:
        packages:
            - google-chrome-stable
branches:
    only:
        - main
        - /^greenkeeper/.*$/

dist: xenial
before_install:
    # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
    - export DISPLAY=:99.0
jobs:
    include:
        - stage: test
          script:
              - npm run test
        - script:
              - docker-compose up -d standalone-chrome-travis
              - USE_SELENIUM_GRID=true WDIO_EXTERNAL_HOST=$(ifconfig | awk '/inet 10/{i++}i==1' | cut -d' ' -f2) npm run test:wdio:local
        - stage: lint
          script: npm run lint
        - stage: build
          script: npm run build
        - script: npm run build:dist
        - stage: release
          node_js: lts/*
          script: skip
          deploy:
              provider: script
              skip_cleanup: true
              script: npx semantic-release
              on:
                  branch: main
        - stage: deploy
          name: "Deploy to gh-pages"
          script: skip
          before_deploy:
              - npm run build:site
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              local_dir: .site
              on:
                  branch: main
stages:
    - lint
    - test
    - build
    - name: release
      if: type != pull_request
    - name: deploy
      if: type != pull_request
