version: '3.7'

services:
    standalone-selenium-hub-travis:
        image: selenium/hub:latest
        ports:
            - "4444:4444"
    standalone-chrome-travis:
        image: selenium/standalone-chrome:latest
        # Necessary due to some issues with chrome in docker.  See https://github.com/SeleniumHQ/docker-selenium#running-the-images
        volumes:
            - '/dev/shm:/dev/shm'
        environment:
            HUB_HOST: hub
            HUB_PORT: 4444
        deploy:
            replicas: 1

    standalone-firefox-travis:
        image: selenium/standalone-firefox:latest
        volumes:
            - '/dev/shm:/dev/shm'
        environment:
            HUB_HOST: hub
            HUB_PORT: 4444
        deploy:
            replicas: 1
