version: '3'

services:

    standalone-selenium-hub-travis:
        image: selenium/hub:${TERRA_SELENIUM_DOCKER_VERSION}
        ports:
            - "4444:4444"
    standalone-chrome-travis:
        image: selenium/node-chrome:${TERRA_SELENIUM_DOCKER_VERSION}
        # Necessary due to some issues with chrome in docker.  See https://github.com/SeleniumHQ/docker-selenium#running-the-images
        volumes:
            - '/dev/shm:/dev/shm'
        environment:
            HUB_HOST: hub
            HUB_PORT: 4444
        deploy:
            replicas: 1

    standalone-firefox-travis:
        image: selenium/node-firefox:${TERRA_SELENIUM_DOCKER_VERSION}
        volumes:
            - '/dev/shm:/dev/shm'
        environment:
            HUB_HOST: hub
            HUB_PORT: 4444
        deploy:
            replicas: 1
