version: '3'

services:
    hub:
        image: selenium/hub:3.14.0-helium
        ports:
            - 4444:4444

    firefox:
        image: selenium/standalone-firefox:3.14.0-helium
        ports:
            - 5900
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
            - HUB_PORT_4444_TCP_PORT=4444
        depends_on:
            - hub

    chrome:
        image: selenium/standalone-chrome:3.14.0-helium
        ports:
            - 5900
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
            - HUB_PORT_4444_TCP_PORT=4444
        depends_on:
            - hub




