version: '3'

services:
    standalone-chrome:
            image: selenium/standalone-chrome:latest
        ports:
            - 4444
        # Necessary due to some issues with chrome in docker.  See https://github.com/SeleniumHQ/docker-selenium#running-the-images
        volumes:
            - '/dev/shm:/dev/shm'
        # Necessary to lock down screen sizes for our screen shot comparisons.
        environment:
            TZ: 'America/Chicago'

    standalone-chrome-travis:
        image: selenium/standalone-chrome:latest
        ports:
            - 4444:4444
        # Necessary due to some issues with chrome in docker.  See https://github.com/SeleniumHQ/docker-selenium#running-the-images
        volumes:
            - '/dev/shm:/dev/shm'
        environment:
            TZ: 'America/Chicago'

volumes:
    zsh_history:
